//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseDeal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuxiliaryWork
    {
        public int Id { get; set; }
        public int AuxiliaryWorkDocumentId { get; set; }
        public System.DateTimeOffset SettedTime { get; set; }
        public System.DateTimeOffset FactTime { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual AuxiliaryWorkDocument AuxiliaryWorkDocument { get; set; }
    }
}
