//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseDeal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryComplexity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryComplexity()
        {
            this.Value = 0D;
        }
    
        public string CategoryId { get; set; }
        public int ComplexityId { get; set; }
        public double Value { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Complexity Complexity { get; set; }
    }
}
