//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseDeal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Name = "Unnamed";
            this.CountingComplexity = false;
            this.Product = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<double> SearchComplexity { get; set; }
        public Nullable<double> PickingComplexity { get; set; }
        public Nullable<double> PackagingComplexity { get; set; }
        public Nullable<double> RankingComplexity { get; set; }
        public bool CountingComplexity { get; set; }
        public bool IsPiecesInDeal { get; set; }
    
        public virtual Category CategoryParent { get; set; }
        public virtual Category CategoryChild { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
