//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseDeal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplexityLimits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComplexityLimits()
        {
            this.MinComplexity = 0D;
            this.MaxComplexity = 0D;
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public double MinComplexity { get; set; }
        public double MaxComplexity { get; set; }
    }
}
