//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseDeal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadingUnloading
    {
        public int Id { get; set; }
        public int LoadingUnloadingDocumentId { get; set; }
        public bool IsLoading { get; set; }
        public double Weight { get; set; }
        public double OrdinaryPackages { get; set; }
        public double EnumerablePackages { get; set; }
    
        public virtual LoadingUnloadingDocument LoadingUnloadingDocument { get; set; }
    }
}
